image: docker:latest

before_script:
  - echo "Before script section"
  - docker info

Build and Deploy:
  stage: build
  script:
    - echo "Building docker image"
    - docker-compose up -d --build
  after_script:
    - docker system prune -f
  only:
    - master
  tags:
    - al-faridah-building-tourview-api