before_script:
  - echo "Before script section"
  - docker info
  - node -v

Build and Deploy:
  stage: build
  script:
    - echo "Building docker image"
    - docker-compose up -d --build
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
    - nvm install node
    - npm i -g yarn
    - yarn
    - yarn global add pm2
    - cp .env.production .env
  after_script:
    - docker system prune -f
    - pm2 start
  only:
    - master
  tags:
    - al-faridah-building-tourview-api