image: node:lts-alpine

before_script:
  - echo "Before script section"
  - docker info

Build and Deploy:
  stage: build
  script:
    - echo "Building docker image"
    - docker-compose up -d --build
    - npm i -g yarn
    - yarn
    - yarn global add pm2
    - cp .env.production .env
  after_script:
    - docker system prune -f
    - pm2 start
  only:
    - master
  tags:
    - al-faridah-building-tourview-api