version: '3'

services:
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:latest
    volumes:
      - /tourview/redis:/data
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - internal
  tourview-api:
    container_name: tourview-api
    restart: unless-stopped
    image: tourview-api
    build:
      context: .
    ports:
      - 8055:8055
    expose:
      - 8055
    networks:
      - internal
networks:
  internal:
    driver: bridge
    