version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - internal
    environment:
      - POSTGRES_USER=tourview
      - POSTGRES_PASSWORD=Tv10293847
      - POSTGRES_DB=tourview
    volumes:
      - /tourview/postgres/tourview:/var/lib/postgresql/data
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:latest
    volumes:
      - tourview-redis:/data
    networks:
      - internal
networks:
  internal:
    driver: bridge
volumes:
  tourview-redis:
    